version: '1'
services:
  node:
    build: 
      context: ./
    ports: 
      - ${PORT}:${PORT}
    # depends_on:
    #   - postgres
    volumes: 
      - .:/app
      - /app/node_modules
    # environment:
    #   - PORT=4000
    # command: 
    #   - server.ts
  # postgres:
  #   build: ./database/
  #   ports: 
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}   
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}